/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_multithreding_Question10_factorial */

#ifndef _Included_com_multithreding_Question10_factorial
#define _Included_com_multithreding_Question10_factorial
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_multithreding_Question10_factorial
 * Method:    fact
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_multithreding_Question10_factorial_fact
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
