/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_multithreding_Question10_fibonacci */

#ifndef _Included_com_multithreding_Question10_fibonacci
#define _Included_com_multithreding_Question10_fibonacci
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_multithreding_Question10_fibonacci
 * Method:    returnfibo
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_multithreding_Question10_fibonacci_returnfibo
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
