/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_multithreding_Question10_daysofweek */

#ifndef _Included_com_multithreding_Question10_daysofweek
#define _Included_com_multithreding_Question10_daysofweek
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_multithreding_Question10_daysofweek
 * Method:    returndays
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_multithreding_Question10_daysofweek_returndays
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
