/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_multithreding_Question10_reverse */

#ifndef _Included_com_multithreding_Question10_reverse
#define _Included_com_multithreding_Question10_reverse
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_multithreding_Question10_reverse
 * Method:    reversefunc
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_multithreding_Question10_reverse_reversefunc
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
