/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_multithreding_Question10_HelloWorld */

#ifndef _Included_com_multithreding_Question10_HelloWorld
#define _Included_com_multithreding_Question10_HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_multithreding_Question10_HelloWorld
 * Method:    cfunction
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_multithreding_Question10_HelloWorld_cfunction
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
